version: '3.8'

services:
  customers-ms:
    build: .
    ports:
      - "8003:8000"
    environment:
      - DB_URL=postgresql://docker:docker@db:5432/customers
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=customers
    volumes:
      - customers_data:/var/lib/postgresql/data

volumes:
  customers_data:
